"""Custom-route bytecode table emitter — `RouteRegistry` -> engine C fragment.

SoT: ``reference/guides/custom_route_interpreter.md`` ("Gen-hook" section).
Modeled on ``sprite_emit.py``'s gen-file emission conventions (GENERATED
header comment, mkdir-parents, byte-stable deterministic output). Writes the
one gen.h fragment the engine's ``uranium_move_routes.gen.h`` hook expects:
``sUraniumRoutes[]``, a 1-indexed ``const u8 *const`` array (index 0 = NULL
sentinel, index k = the k-th distinct interned route's bytecode array).

Both the per-route arrays and the index table are ``const`` deliberately —
the GBA linker discards nonzero non-const file-scope statics, a build gotcha
called out in the contract doc's "Engine registration" section.
"""
from __future__ import annotations

import logging
from pathlib import Path

from rpg2gba.tileset_converter.route_bytecode import RouteRegistry

logger = logging.getLogger(__name__)

_GEN_RELPATH = Path("src/data/object_events/uranium_move_routes.gen.h")

_GENERATED_HEADER = (
    "// GENERATED by rpg2gba — do not edit; regenerate via emit_route_table().\n"
)

_STUB_BODY = "const u8 *const sUraniumRoutes[] = { NULL };\n"


def _render(registry: RouteRegistry) -> str:
    routes = registry.routes()
    if not routes:
        return _GENERATED_HEADER + _STUB_BODY

    lines = [_GENERATED_HEADER]
    for i, route in enumerate(routes):
        route_id = i + 1
        values = ", ".join(f"0x{b:02x}" for b in route)
        lines.append(f"static const u8 sUraniumRoute_{route_id}[] = {{ {values} }};\n")

    entries = ", ".join(f"sUraniumRoute_{i + 1}" for i in range(len(routes)))
    lines.append(f"const u8 *const sUraniumRoutes[] = {{ NULL, {entries} }};\n")
    return "".join(lines)


def emit_route_table(registry: RouteRegistry, engine_root: Path) -> None:
    """Write ``uranium_move_routes.gen.h`` under `engine_root` from `registry`.

    Distinct routes (``registry.routes()``, 0-based index ``i`` = route id
    ``i + 1``) each become a `static const u8 sUraniumRoute_{id}[]` array; the
    index table `sUraniumRoutes[]` follows, NULL at index 0. An empty
    registry writes the zero-route stub (see `write_stub`) so a fresh clone
    with no staged routes still compiles.
    """
    engine_root = Path(engine_root)
    path = engine_root / _GEN_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_render(registry), encoding="utf-8")
    logger.debug(
        "emit_route_table: %d distinct routes -> %s", len(registry), path
    )


def write_stub(engine_root: Path) -> None:
    """Write the zero-route stub form (`sUraniumRoutes[] = { NULL };`) so a
    fresh clone with no routes staged still compiles against the engine's
    gen-hook `#include`."""
    engine_root = Path(engine_root)
    path = engine_root / _GEN_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_GENERATED_HEADER + _STUB_BODY, encoding="utf-8")
