"""Unit tests for `pbs_converter._c_emit`."""
from __future__ import annotations

from rpg2gba.pbs_converter._c_emit import (
    escape_c_string,
    generated_banner,
    wrap_header,
)


def test_escape_c_string_passthrough_ascii() -> None:
    assert escape_c_string("Pokeball") == "Pokeball"


def test_escape_c_string_quotes_and_backslash() -> None:
    assert escape_c_string('say "hi" \\ done') == 'say \\"hi\\" \\\\ done'


def test_escape_c_string_control_and_high_bytes() -> None:
    # newline → \n, Windows-1252 é (0xE9) → \xE9
    assert escape_c_string("line1\nlin\xE9") == "line1\\nlin\\xE9"


def test_wrap_header_emits_guards() -> None:
    out = wrap_header("MY_GUARD_H", "int x = 1;")
    assert out.startswith("#ifndef MY_GUARD_H\n#define MY_GUARD_H\n")
    assert "int x = 1;\n" in out
    assert out.rstrip().endswith("#endif // MY_GUARD_H")


def test_wrap_header_with_banner() -> None:
    banner = "// DO NOT EDIT — generated by test\n"
    out = wrap_header("G", "void f(void);", banner=banner)
    assert out.startswith(banner)
    assert "#ifndef G" in out


def test_generated_banner_names_source_and_module() -> None:
    b = generated_banner("dexdata.dat", "rpg2gba.pbs_converter.pokemon")
    assert "dexdata.dat" in b
    assert "rpg2gba.pbs_converter.pokemon" in b
    assert "DO NOT EDIT" in b
