"""Tests for `route_table_emit` — RouteRegistry -> engine gen.h fragment."""
from __future__ import annotations

from pathlib import Path

from rpg2gba.tileset_converter.route_bytecode import RouteRegistry
from rpg2gba.tileset_converter.route_table_emit import emit_route_table, write_stub

_GEN_RELPATH = Path("src/data/object_events/uranium_move_routes.gen.h")


def test_empty_registry_writes_stub(tmp_path: Path) -> None:
    registry = RouteRegistry()
    emit_route_table(registry, tmp_path)

    content = (tmp_path / _GEN_RELPATH).read_text(encoding="utf-8")
    assert "GENERATED by rpg2gba" in content
    assert "const u8 *const sUraniumRoutes[] = { NULL };" in content
    assert "sUraniumRoute_" not in content


def test_write_stub_matches_empty_registry_output(tmp_path: Path) -> None:
    write_stub(tmp_path)

    content = (tmp_path / _GEN_RELPATH).read_text(encoding="utf-8")
    assert "GENERATED by rpg2gba" in content
    assert content.strip().endswith("const u8 *const sUraniumRoutes[] = { NULL };")


def test_two_distinct_routes_emit_arrays_and_index_table(tmp_path: Path) -> None:
    registry = RouteRegistry()
    registry.intern([102, 0x02, 0x03, 0x00])
    registry.intern([102, 0x01, 0x04, 0x00])

    emit_route_table(registry, tmp_path)

    content = (tmp_path / _GEN_RELPATH).read_text(encoding="utf-8")
    assert (
        "static const u8 sUraniumRoute_1[] = { 0x66, 0x02, 0x03, 0x00 };" in content
    )
    assert (
        "static const u8 sUraniumRoute_2[] = { 0x66, 0x01, 0x04, 0x00 };" in content
    )
    assert (
        "const u8 *const sUraniumRoutes[] = "
        "{ NULL, sUraniumRoute_1, sUraniumRoute_2 };" in content
    )


def test_dedup_same_bytecode_yields_one_route(tmp_path: Path) -> None:
    registry = RouteRegistry()
    id_a = registry.intern([102, 0x02, 0x03, 0x00])
    id_b = registry.intern([102, 0x02, 0x03, 0x00])

    assert id_a == id_b == 1
    assert len(registry) == 1

    emit_route_table(registry, tmp_path)

    content = (tmp_path / _GEN_RELPATH).read_text(encoding="utf-8")
    assert content.count("static const u8 sUraniumRoute_") == 1
    assert (
        "const u8 *const sUraniumRoutes[] = { NULL, sUraniumRoute_1 };" in content
    )
