"""Shared helpers for emitting C source from Phase 2 converters."""
from __future__ import annotations

from datetime import UTC, datetime

_ESCAPES = {
    ord("\\"): "\\\\",
    ord('"'): '\\"',
    ord("\n"): "\\n",
    ord("\r"): "\\r",
    ord("\t"): "\\t",
    ord("\0"): "\\0",
}


def escape_c_string(s: str) -> str:
    """Escape a string for embedding inside C double quotes.

    Non-printable bytes outside ASCII become `\\x%02X` escapes. Uranium strings
    can contain Windows-1252 high bytes (accented chars, the section symbol used
    in some Pokédex entries); those round-trip through `\\x%02X` so the C source
    stays pure ASCII.
    """
    out: list[str] = []
    for ch in s:
        cp = ord(ch)
        if cp in _ESCAPES:
            out.append(_ESCAPES[cp])
        elif 0x20 <= cp <= 0x7E:
            out.append(ch)
        elif cp <= 0xFF:
            out.append(f"\\x{cp:02X}")
        else:
            out.append(f"\\u{cp:04X}")
    return "".join(out)


def generated_banner(source_dat: str, generator_module: str, *, timestamp: bool = True) -> str:
    """Standard top-of-file banner for every emitted artifact.

    Names the source .dat (or "multiple sources") and the rpg2gba module that
    produced this file. Used by humans and by the round-trip tests to confirm
    that they're reading a generated file before parsing.

    Pass `timestamp=False` for files that must be byte-identical across runs
    (CLAUDE.md §4.2 idempotence / PHASE2_PLAN.md V4 `diff -r`). A timestamped
    banner would make every re-run differ.
    """
    lines = [
        f"// DO NOT EDIT — generated by {generator_module}",
        f"// source: {source_dat}",
    ]
    if timestamp:
        when = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines.append(f"// generated: {when}")
    return "\n".join(lines) + "\n"


def wrap_header(guard: str, body: str, *, banner: str = "") -> str:
    """Wrap C declarations in include-once guards."""
    parts = [banner] if banner else []
    parts.extend([
        f"#ifndef {guard}\n#define {guard}\n",
        body.rstrip() + "\n",
        f"\n#endif // {guard}\n",
    ])
    return "".join(parts)
