"""Recurring rung-2 assembly smoke check for the Phase 4 bulk conversion run.

Compile ALL currently emitted Poryscript output (.pory → .inc), drop them into a
throwaway git worktree of the pokeemerald-expansion fork together with generated
support headers, run ``make modern``, and cluster the assembly errors (duplicate
symbols, undefined references).

The per-event compile gate cannot see assembly-class bugs that span multiple
compiled files: duplicate labels across maps, constants that compile clean in
isolation but are unresolvable at link/assemble time.  This script catches them.
Run it between bulk rounds while the machine idles on the 5-hour pause window.

Design rationale: FABLES_DECISIONS.md "Suggestion 4 — Recurring rung-2 assembly
smoke check".  Proven manual wiring: reference/memory-archive.md "Rung-2
derisking spike" (branch rung2-map200-spike, 2026-05-31).

Usage (most common):
  python scripts/assembly_smoke.py               # prepare → build → report
  python scripts/assembly_smoke.py --prepare-only  # stage only; build later

Subcommands:
  prepare   Compile .pory→.inc, generate support headers, wire includes
  build     Run make -j<nproc> modern in the smoke worktree (takes minutes)
  report    Parse smoke-build.log and print error clusters
  teardown  Remove the worktree and delete the throwaway branch
"""
from __future__ import annotations

import argparse
import json
import logging
import multiprocessing
import os
import re
import subprocess
import sys
from pathlib import Path

from rpg2gba import pipeline

logger = logging.getLogger("assembly_smoke")

# ---------------------------------------------------------------------------
# Repository-layout constants
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SMOKE_WORKTREE = _REPO_ROOT / "output" / "smoke-worktree"
_SMOKE_BRANCH = "rpg2gba-smoke-branch"
_BUILD_LOG = _REPO_ROOT / "output" / "smoke-build.log"

# Relative to the smoke worktree
_SMOKE_INC_SUBDIR = Path("data") / "scripts" / "rpg2gba_smoke"

# Idempotency markers for the two wiring blocks in event_scripts.s
_HDR_BEGIN = "@ rpg2gba-smoke-headers begin"
_HDR_END = "@ rpg2gba-smoke-headers end"
_SCR_BEGIN = "@ rpg2gba-smoke-scripts begin"
_SCR_END = "@ rpg2gba-smoke-scripts end"

# Line in event_scripts.s before which we insert the constants-header block.
# This line sits at the natural boundary between the #include section and the
# .include / .section assembler directives (verified in rung-2 spike notes).
_HDR_ANCHOR = '.include "asm/macros.inc"'

# ---------------------------------------------------------------------------
# Pure helpers — no git, no make, no binary (fully unit-testable)
# ---------------------------------------------------------------------------

_MAP_TOKEN_RE = re.compile(r"\bMAP_URANIUM_(\d+)\b")
_TRAINER_TOKEN_RE = re.compile(r"\bTRAINER_[A-Z0-9_]+\b")
_ALLCAPS_RE = re.compile(r"\b([A-Z][A-Z0-9_]{2,})\b")


def scan_map_tokens(text: str) -> set[str]:
    """Return all distinct MAP_URANIUM_<N> token names referenced in *text*."""
    return {m.group(0) for m in _MAP_TOKEN_RE.finditer(text)}


def emit_map_aliases_header(tokens: set[str], target_map_const: str) -> str:
    """Emit a C header that #define-aliases every MAP_URANIUM_<N> token.

    Each alias points to *target_map_const* (the first MAP_* defined in the
    fork's include/constants/map_groups.h, e.g. MAP_PETALBURG_CITY).

    Why this works with the warp macro: the ``warp``/``formatwarp`` GAS macros
    call ``.ifdef \\map_id`` on the map argument.  The C preprocessor runs BEFORE
    the assembler; by the time the assembler sees the code, ``MAP_URANIUM_N`` has
    already been textually substituted to ``MAP_PETALBURG_CITY``.  The ``.ifdef``
    then tests the real assembler symbol, which passes.  Verified by reading
    ``asm/macros/map.inc``::``map`` macro (lines 4–11: ``.ifdef \\map_id; .byte
    \\map_id >> 8; .byte \\map_id & 0xFF; .else; .error ...; .endif``).
    """
    lines = [
        "#ifndef GUARD_RPG2GBA_MAP_ALIASES_H",
        "#define GUARD_RPG2GBA_MAP_ALIASES_H",
        "",
        "// Generated by scripts/assembly_smoke.py — do not hand-edit.",
        "// Placeholder MAP_URANIUM_<N> aliases for smoke assembly.",
        "// Every alias resolves to the fork's first MAP_* constant, a plain integer",
        "// expression.  The C preprocessor substitutes these before the assembler",
        "// sees them, so the warp macro's .ifdef check passes correctly.",
        f"// Verified alias target: {target_map_const}",
        "",
    ]
    for token in sorted(tokens, key=lambda t: int(t.split("_")[-1])):
        lines.append(f"#define {token} {target_map_const}")
    lines += ["", "#endif  // GUARD_RPG2GBA_MAP_ALIASES_H", ""]
    return "\n".join(lines)


def scan_trainer_tokens(text: str) -> set[str]:
    """Return all distinct TRAINER_[A-Z0-9_]+ token names referenced in *text*."""
    return set(_TRAINER_TOKEN_RE.findall(text))


def emit_trainer_aliases_header(
    tokens: set[str],
    trainer_ids: dict[str, int],
    fork_trainer_consts: set[str],
) -> str:
    """Emit a C header defining TRAINER_* integer ids from trainers.json.

    Args:
        tokens: every TRAINER_* token found in compiled .inc output.
        trainer_ids: mapping ``TRAINER_CONSTANT -> integer_id`` from
            ``output/uranium-build/intermediate/trainers.json``.
        fork_trainer_consts: TRAINER_* names already defined in the fork's
            ``include/constants/opponents.h`` and related headers — skipped to
            avoid redefinition errors.

    Tokens that appear in neither ``fork_trainer_consts`` nor ``trainer_ids``
    are left undefined; the fail-loud ``find_unresolved_families`` check catches
    them after all three headers have been generated.
    """
    lines = [
        "#ifndef GUARD_RPG2GBA_TRAINER_ALIASES_H",
        "#define GUARD_RPG2GBA_TRAINER_ALIASES_H",
        "",
        "// Generated by scripts/assembly_smoke.py — do not hand-edit.",
        "// Uranium TRAINER_* constants from output/uranium-build/intermediate/trainers.json.",
        "// Only constants referenced in compiled output that are absent from opponents.h",
        "// are emitted here.",
        "",
    ]
    defined_any = False
    for token in sorted(tokens):
        if token in fork_trainer_consts:
            continue  # already defined in the fork — do not redefine
        if token in trainer_ids:
            lines.append(f"#define {token} {trainer_ids[token]}")
            defined_any = True
        # tokens in neither: silently omitted; fail-loud check handles them
    if not defined_any:
        lines.append("// (no Uranium-specific TRAINER_* constants in current compiled output)")
    lines += ["", "#endif  // GUARD_RPG2GBA_TRAINER_ALIASES_H", ""]
    return "\n".join(lines)


def find_unresolved_families(
    text: str,
    all_known: set[str],
) -> dict[str, list[str]]:
    """Scan compiled .inc text for ALL_CAPS tokens not in *all_known*.

    Groups unknown tokens by their prefix family (the first word before ``_``).
    Returns ``{family: [example_token, ...]}``.  An empty dict means every
    referenced constant resolves against the fork headers or a generated header.

    Only considers tokens that contain at least one underscore — bare ALL_CAPS
    words (``PUSH``, ``LDR``, ``BL``) are GAS/ARM mnemonics, not constant names.
    """
    unresolved: dict[str, list[str]] = {}
    seen: set[str] = set()
    for token in _ALLCAPS_RE.findall(text):
        if token in all_known or token in seen:
            continue
        seen.add(token)
        if "_" not in token:
            continue  # GAS mnemonic or bare short word — skip
        family = token.split("_")[0]
        unresolved.setdefault(family, []).append(token)
    return unresolved


def cluster_build_errors(log_text: str) -> dict[str, object]:
    r"""Parse a make build log into error clusters.

    Recognises three error classes:

    * **Duplicate symbol definitions** — GAS assembler:
      ``Error: symbol \`LABEL' is already defined``
    * **Undefined references** — GNU ld:
      ``undefined reference to \`SYMBOL'``
    * **Other errors** — any line containing ``Error:`` or ``error:``
      not matched by the above patterns.

    Returns::

        {
            "duplicate_symbols": list[str],           # deduped symbol names
            "undefined_by_family": dict[str, list[str]],  # prefix → names
            "other_errors": list[str],                # raw error text lines
        }
    """
    _DUP_RE = re.compile(r"symbol `([^']+)' is already defined")
    _UNDEF_RE = re.compile(r"undefined reference to `([^']+)'")

    dup_symbols: list[str] = []
    dup_seen: set[str] = set()
    undef_refs: list[str] = []
    undef_seen: set[str] = set()
    other_errors: list[str] = []
    other_seen: set[str] = set()

    for line in log_text.splitlines():
        dm = _DUP_RE.search(line)
        if dm:
            sym = dm.group(1)
            if sym not in dup_seen:
                dup_symbols.append(sym)
                dup_seen.add(sym)
            continue

        um = _UNDEF_RE.search(line)
        if um:
            sym = um.group(1)
            if sym not in undef_seen:
                undef_refs.append(sym)
                undef_seen.add(sym)
            continue

        stripped = line.strip()
        if stripped and ("Error:" in stripped or "error:" in stripped):
            if stripped not in other_seen:
                other_errors.append(stripped)
                other_seen.add(stripped)

    # Group undefined refs by prefix family (first word before "_")
    undef_by_family: dict[str, list[str]] = {}
    for sym in undef_refs:
        family = sym.split("_")[0] if "_" in sym else sym
        undef_by_family.setdefault(family, []).append(sym)

    return {
        "duplicate_symbols": dup_symbols,
        "undefined_by_family": undef_by_family,
        "other_errors": other_errors,
    }


def wire_includes(
    source: str,
    header_lines: list[str],
    script_lines: list[str],
) -> str:
    """Return event_scripts.s text with rpg2gba smoke includes wired in.

    Idempotent: uses marker comments (``@ rpg2gba-smoke-headers begin/end`` and
    ``@ rpg2gba-smoke-scripts begin/end``) to bracket the inserted blocks.
    Running twice with identical arguments produces identical output; running
    with updated arguments replaces the old block wholesale.

    Header ``#include`` lines are inserted just before the
    ``'.include "asm/macros.inc"'`` anchor (the natural boundary between the C
    preprocessor ``#include`` section and the GAS ``.include`` section in
    event_scripts.s, confirmed in the rung-2 spike narrative).  Script
    ``.include`` lines are appended at the end of the file.
    """
    header_block = "\n".join([_HDR_BEGIN] + header_lines + [_HDR_END])
    scripts_block = "\n".join([_SCR_BEGIN] + script_lines + [_SCR_END])

    # -- headers block --------------------------------------------------------
    if _HDR_BEGIN in source and _HDR_END in source:
        # Replace existing block wholesale (idempotent update)
        pat = re.compile(
            re.escape(_HDR_BEGIN) + r".*?" + re.escape(_HDR_END), re.DOTALL
        )
        source = pat.sub(header_block, source, count=1)
    else:
        # First insertion: add before the anchor line (preserving its indentation)
        src_lines = source.splitlines(keepends=True)
        inserted = False
        for i, line in enumerate(src_lines):
            if _HDR_ANCHOR in line:
                src_lines.insert(i, header_block + "\n")
                inserted = True
                break
        source = "".join(src_lines) if inserted else header_block + "\n" + source

    # -- scripts block --------------------------------------------------------
    if _SCR_BEGIN in source and _SCR_END in source:
        pat = re.compile(
            re.escape(_SCR_BEGIN) + r".*?" + re.escape(_SCR_END), re.DOTALL
        )
        source = pat.sub(scripts_block, source, count=1)
    else:
        source = source.rstrip("\n") + "\n" + scripts_block + "\n"

    return source


# ---------------------------------------------------------------------------
# Fork / runtime helpers — depend on disk state; not directly unit-tested
# ---------------------------------------------------------------------------

def _get_first_map_const(fork_path: Path) -> str:
    """Return the first MAP_* constant name from the fork's map_groups.h."""
    h = fork_path / "include" / "constants" / "map_groups.h"
    text = h.read_text(encoding="utf-8")
    m = re.search(r"\b(MAP_[A-Z][A-Z0-9_]+)\s*=", text)
    if not m:
        raise RuntimeError(f"No MAP_* constant found in {h}")
    return m.group(1)


def _load_fork_trainer_consts(fork_path: Path) -> set[str]:
    """Return all TRAINER_* names defined in the fork's include/constants/ headers."""
    result: set[str] = set()
    for h in (fork_path / "include" / "constants").glob("*.h"):
        try:
            text = h.read_text(encoding="utf-8")
        except OSError:
            continue
        result.update(re.findall(r"#define\s+(TRAINER_[A-Z0-9_]+)", text))
    return result


def _load_trainers_id_map(out_dir: Path) -> dict[str, int]:
    """Load TRAINER_* constant → integer array-index id from trainers.json.

    The ``id`` field in trainers.json is the Marshal array index (the position
    of the trainer in trainers.dat), which is the integer the engine uses to
    identify a trainer battle.  Matches the key suffix in the constant name,
    e.g. ``TRAINER_ABE_GAYLE_166`` → ``id: 166``.
    """
    path = out_dir / "intermediate" / "trainers.json"
    if not path.is_file():
        raise FileNotFoundError(
            f"trainers.json not found at {path} — "
            "run `python -m rpg2gba.pipeline phase2` first"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    trainers: dict = data.get("trainers", {})
    return {key: int(val["id"]) for key, val in trainers.items()}


def _load_all_fork_constants(fork_path: Path) -> set[str]:
    """Build the set of all ALL_CAPS identifiers visible from event_scripts.s.

    Scans ``include/constants/*.h`` (``#define``-d flag/item/map/trainer
    constants) and ``asm/macros/*.inc`` (GAS equates like ``MSGBOX_NPC = 2``
    and ``MSGBOX_YESNO = 5`` from event.inc).  The union covers every constant
    the fork's assembler can resolve without our custom headers.
    """
    result: set[str] = set()
    for scan_dir in (
        fork_path / "include" / "constants",
        fork_path / "asm" / "macros",
    ):
        for suffix in ("*.h", "*.inc"):
            for f in scan_dir.glob(suffix):
                try:
                    result.update(_ALLCAPS_RE.findall(f.read_text(encoding="utf-8")))
                except OSError:
                    pass
    return result


def _read_header_constants(header_path: Path) -> set[str]:
    """Extract ALL_CAPS identifiers from a generated header file."""
    if not header_path.is_file():
        return set()
    return set(_ALLCAPS_RE.findall(header_path.read_text(encoding="utf-8")))


def _compile_pory_to_inc(pory_path: Path, inc_path: Path) -> tuple[bool, str]:
    """Invoke poryscript to compile *pory_path* → *inc_path*.

    Returns ``(ok, stderr)``.  Raises ``RuntimeError`` if the binary is absent.
    """
    from rpg2gba.conversion_agent.poryscript import (
        PoryscriptUnavailable,
        _config_args,
        binary_path,
    )

    try:
        binary = binary_path()
    except PoryscriptUnavailable as exc:
        raise RuntimeError(str(exc)) from exc

    inc_path.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        [str(binary), "-i", str(pory_path), "-o", str(inc_path), *_config_args(binary)],
        capture_output=True,
        text=True,
    )
    return proc.returncode == 0, proc.stderr


def _create_or_reuse_worktree(
    fork_path: Path,
    worktree_path: Path,
    branch: str,
) -> None:
    """Create a git worktree on *branch* in *worktree_path*, or reuse if it exists.

    NEVER touches the fork's main checkout working tree.
    """
    if worktree_path.is_dir():
        logger.info("reusing existing worktree at %s", worktree_path)
        return

    worktree_path.parent.mkdir(parents=True, exist_ok=True)

    # Does the throwaway branch already exist in the fork?
    r = subprocess.run(
        ["git", "-C", str(fork_path), "rev-parse", "--verify", branch],
        capture_output=True,
        text=True,
    )
    if r.returncode == 0:
        # Branch exists — attach the new worktree to it
        cmd = [
            "git", "-C", str(fork_path),
            "worktree", "add", str(worktree_path), branch,
        ]
    else:
        # Branch absent — create it from fork HEAD
        cmd = [
            "git", "-C", str(fork_path),
            "worktree", "add", "-b", branch, str(worktree_path),
        ]
    subprocess.run(cmd, check=True)
    logger.info("created worktree at %s on branch %s", worktree_path, branch)


def _teardown_worktree(
    fork_path: Path,
    worktree_path: Path,
    branch: str,
) -> None:
    """Remove the git worktree and delete the throwaway branch."""
    subprocess.run(
        ["git", "-C", str(fork_path), "worktree", "remove", "--force", str(worktree_path)],
        check=True,
    )
    subprocess.run(
        ["git", "-C", str(fork_path), "branch", "-D", branch],
        check=True,
    )
    logger.info("worktree removed and branch %s deleted", branch)


# ---------------------------------------------------------------------------
# Subcommand implementations
# ---------------------------------------------------------------------------

def cmd_prepare(fork_path: Path, out_dir: Path, define_unresolved: bool = False) -> int:
    """Compile .pory→.inc, generate support headers, wire includes idempotently."""
    scripts_dir = out_dir / "scripts"
    pory_files = sorted(scripts_dir.glob("*.pory"))
    if not pory_files:
        logger.error("no .pory files found in %s — run phase4 first", scripts_dir)
        return 1

    # 1. Create or reuse the throwaway worktree
    _create_or_reuse_worktree(fork_path, _SMOKE_WORKTREE, _SMOKE_BRANCH)

    # 2. Compile every .pory → .inc
    smoke_inc_dir = _SMOKE_WORKTREE / _SMOKE_INC_SUBDIR
    smoke_inc_dir.mkdir(parents=True, exist_ok=True)

    compile_failures: list[str] = []
    compiled_inc_files: list[Path] = []

    for pory_file in pory_files:
        inc_path = smoke_inc_dir / (pory_file.stem + ".inc")
        try:
            ok, stderr = _compile_pory_to_inc(pory_file, inc_path)
        except RuntimeError as exc:
            logger.error("poryscript unavailable — cannot compile .pory files: %s", exc)
            return 1
        if not ok:
            logger.warning(
                "transpile failure (finding): %s — %s",
                pory_file.name,
                stderr.strip()[:300],
            )
            compile_failures.append(pory_file.stem)
            continue
        compiled_inc_files.append(inc_path)

    if compile_failures:
        logger.warning(
            "%d transpile failure(s) — skipped, recorded as findings: %s",
            len(compile_failures),
            ", ".join(compile_failures),
        )

    if not compiled_inc_files:
        logger.error("all .pory files failed to transpile — nothing to assemble")
        return 1

    all_inc_text = "\n".join(
        f.read_text(encoding="utf-8") for f in compiled_inc_files
    )

    # 3a. Flag/var header from the live registry (read-only, clean=False)
    registry = pipeline._phase4_registry(out_dir, clean=False, fork_path=fork_path)
    flags_h = _SMOKE_WORKTREE / "include" / "constants" / "rpg2gba_flags.h"
    registry.dump_header(flags_h)

    # 3b. Map aliases header
    map_tokens = scan_map_tokens(all_inc_text)
    logger.info("MAP_URANIUM_* tokens in compiled output: %d", len(map_tokens))
    target_map_const = _get_first_map_const(fork_path)
    logger.info("alias target constant: %s", target_map_const)
    map_aliases_h = _SMOKE_WORKTREE / "include" / "constants" / "rpg2gba_map_aliases.h"
    map_aliases_h.parent.mkdir(parents=True, exist_ok=True)
    map_aliases_h.write_text(
        emit_map_aliases_header(map_tokens, target_map_const),
        encoding="utf-8",
    )

    # 3c. Trainer aliases header
    trainer_tokens = scan_trainer_tokens(all_inc_text)
    fork_trainer_consts = _load_fork_trainer_consts(fork_path)
    try:
        trainers_id_map = _load_trainers_id_map(out_dir)
    except FileNotFoundError as exc:
        logger.warning("trainers.json unavailable — TRAINER_* aliases omitted: %s", exc)
        trainers_id_map = {}
    trainer_h = _SMOKE_WORKTREE / "include" / "constants" / "rpg2gba_trainer_aliases.h"
    trainer_h.parent.mkdir(parents=True, exist_ok=True)
    trainer_h.write_text(
        emit_trainer_aliases_header(trainer_tokens, trainers_id_map, fork_trainer_consts),
        encoding="utf-8",
    )

    # 3d. Fail-loud check: any constant family still unresolved is a genuine bug
    all_known: set[str] = _load_all_fork_constants(fork_path)
    for h in (flags_h, map_aliases_h, trainer_h):
        all_known |= _read_header_constants(h)
    unresolved = find_unresolved_families(all_inc_text, all_known)
    unresolved_h = _SMOKE_WORKTREE / "include" / "constants" / "rpg2gba_smoke_unresolved.h"
    if unresolved and not define_unresolved:
        lines = [
            "ERROR: unresolved constant families in compiled output (CLAUDE.md §4.5).",
            "These families are referenced in assembled scripts but not defined by",
            "any fork header or generated support header.  Add a header for each family,",
            "fix the converter that emitted these tokens, or — once each family is",
            "recorded as a finding — re-run with --define-unresolved to dummy-define",
            "them (smoke worktree only) so the build can proceed.",
            "",
        ]
        for fam, syms in sorted(unresolved.items()):
            examples = syms[:3]
            lines.append(f"  {fam}:  {len(syms)} token(s) — e.g. {examples}")
        print("\n".join(lines), file=sys.stderr)
        return 1
    if unresolved:
        # Opt-in: dummy-define every unresolved token to 0 in a smoke-only header.
        # The FINDING is the unresolved name itself (recorded loudly below); the
        # dummy value exists solely so assembly reaches the duplicate-symbol /
        # undefined-reference checks this harness is for.
        hdr = [
            "#ifndef GUARD_RPG2GBA_SMOKE_UNRESOLVED_H",
            "#define GUARD_RPG2GBA_SMOKE_UNRESOLVED_H",
            "",
            "// Generated by scripts/assembly_smoke.py --define-unresolved — do not hand-edit.",
            "// SMOKE-ONLY dummies for constants with no real definition. Each name here",
            "// is a recorded conversion finding, NOT a resolved constant.",
            "",
        ]
        for fam, syms in sorted(unresolved.items()):
            logger.warning(
                "FINDING — unresolved %s family: %d token(s): %s",
                fam, len(syms), ", ".join(sorted(syms)),
            )
            for sym in sorted(syms):
                hdr.append(f"#define {sym} 0")
        hdr += ["", "#endif  // GUARD_RPG2GBA_SMOKE_UNRESOLVED_H", ""]
        unresolved_h.write_text("\n".join(hdr), encoding="utf-8")
    elif unresolved_h.exists():
        unresolved_h.unlink()  # stale dummies from a prior run must not mask fixes

    # 4. Wire includes into the worktree's event_scripts.s (idempotent)
    event_scripts_s = _SMOKE_WORKTREE / "data" / "event_scripts.s"
    source = event_scripts_s.read_text(encoding="utf-8")

    header_includes = [
        '#include "constants/rpg2gba_flags.h"',
        '#include "constants/rpg2gba_map_aliases.h"',
        '#include "constants/rpg2gba_trainer_aliases.h"',
    ]
    if unresolved_h.exists():
        header_includes.append('#include "constants/rpg2gba_smoke_unresolved.h"')
    script_includes = [
        f'.include "{_SMOKE_INC_SUBDIR.as_posix()}/{inc.name}"'
        for inc in sorted(compiled_inc_files, key=lambda p: p.name)
    ]

    new_source = wire_includes(source, header_includes, script_includes)
    event_scripts_s.write_text(new_source, encoding="utf-8")

    logger.info(
        "prepare complete: %d .inc files compiled, %d transpile failure(s); "
        "worktree: %s",
        len(compiled_inc_files),
        len(compile_failures),
        _SMOKE_WORKTREE,
    )
    return 0


def cmd_build(out_dir: Path) -> int:
    """Run ``make -j<nproc> modern`` in the smoke worktree; capture to smoke-build.log."""
    if not _SMOKE_WORKTREE.is_dir():
        logger.error("worktree not found at %s — run `prepare` first", _SMOKE_WORKTREE)
        return 1

    nproc = multiprocessing.cpu_count()
    _BUILD_LOG.parent.mkdir(parents=True, exist_ok=True)

    print(f"Running make -j{nproc} modern in {_SMOKE_WORKTREE}", flush=True)
    print(
        "Note: the FIRST build is a full ROM compile and takes several minutes.\n"
        "Subsequent incremental builds (unchanged sources) are much faster.",
        flush=True,
    )

    proc = subprocess.run(
        ["make", f"-j{nproc}", "modern"],
        cwd=str(_SMOKE_WORKTREE),
        capture_output=True,
        text=True,
    )
    combined = proc.stdout + "\n" + proc.stderr
    _BUILD_LOG.write_text(combined, encoding="utf-8")

    if proc.returncode == 0:
        print(f"Build SUCCEEDED.  Log: {_BUILD_LOG}")
    else:
        print(f"Build FAILED (exit {proc.returncode}).  Log: {_BUILD_LOG}")
    return proc.returncode


def cmd_report() -> int:
    """Parse smoke-build.log and print a clustered error summary."""
    if not _BUILD_LOG.is_file():
        logger.error("build log not found at %s — run `build` first", _BUILD_LOG)
        return 1

    log_text = _BUILD_LOG.read_text(encoding="utf-8")
    clusters = cluster_build_errors(log_text)

    dup_syms: list[str] = clusters["duplicate_symbols"]  # type: ignore[assignment]
    undef_by_fam: dict[str, list[str]] = clusters["undefined_by_family"]  # type: ignore[assignment]
    other: list[str] = clusters["other_errors"]  # type: ignore[assignment]

    total_undef = sum(len(v) for v in undef_by_fam.values())
    total = len(dup_syms) + total_undef + len(other)

    print("\n=== Assembly Smoke Report ===")
    print(f"Log: {_BUILD_LOG}\n")

    print(f"Duplicate symbols: {len(dup_syms)}")
    for sym in dup_syms[:3]:
        print(f"  {sym}")
    if len(dup_syms) > 3:
        print(f"  ... and {len(dup_syms) - 3} more")

    print(f"\nUndefined references: {total_undef} total across {len(undef_by_fam)} families")
    for fam, syms in sorted(undef_by_fam.items()):
        extras = f" (+{len(syms) - 3} more)" if len(syms) > 3 else ""
        print(f"  {fam:20s}  {len(syms):4d}  e.g. {syms[:3]}{extras}")

    print(f"\nOther errors: {len(other)}")
    for line in other[:3]:
        print(f"  {line}")
    if len(other) > 3:
        print(f"  ... and {len(other) - 3} more")

    if total == 0:
        print("\nClean build — no assembly-class findings.")
        return 0
    print(f"\n{total} total finding(s).")
    return 1


def cmd_teardown(fork_path: Path) -> int:
    """Remove the smoke worktree and delete the throwaway branch."""
    if not _SMOKE_WORKTREE.is_dir():
        logger.info("worktree not found at %s — nothing to tear down", _SMOKE_WORKTREE)
        return 0
    _teardown_worktree(fork_path, _SMOKE_WORKTREE, _SMOKE_BRANCH)
    print(f"Torn down: {_SMOKE_WORKTREE}; branch {_SMOKE_BRANCH} deleted.")
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--prepare-only",
        action="store_true",
        help=(
            "Stage the worktree (compile + headers + wiring) without running the build. "
            "Use this to set everything up at a convenient time and run `build` later "
            "when authorised."
        ),
    )
    ap.add_argument(
        "--define-unresolved",
        action="store_true",
        help=(
            "During prepare, dummy-define (to 0, smoke worktree only) any constant "
            "the fail-loud check finds unresolved, instead of aborting. Each token is "
            "logged as a FINDING. Use only after the families have been recorded."
        ),
    )
    ap.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable DEBUG-level logging.",
    )

    sub = ap.add_subparsers(dest="cmd")
    sub.add_parser(
        "prepare",
        help="Compile .pory→.inc, generate support headers, wire includes.",
    )
    sub.add_parser(
        "build",
        help="Run make -j<nproc> modern in the smoke worktree (takes minutes).",
    )
    sub.add_parser(
        "report",
        help="Parse smoke-build.log and print error clusters.",
    )
    sub.add_parser(
        "teardown",
        help="Remove the smoke worktree and delete the throwaway branch.",
    )

    args = ap.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    pipeline._load_dotenv()

    fork_str = os.environ.get("RPG2GBA_POKEEMERALD")
    if not fork_str:
        print(
            "ERROR: RPG2GBA_POKEEMERALD is not set "
            "(add it to .env-paths or your shell environment)",
            file=sys.stderr,
        )
        return 1
    fork_path = Path(fork_str)
    if not fork_path.is_dir():
        print(
            f"ERROR: RPG2GBA_POKEEMERALD={fork_path} is not a directory",
            file=sys.stderr,
        )
        return 1

    _, out_dir_raw = pipeline._resolve_paths()
    out_dir = Path(out_dir_raw)

    if args.cmd == "prepare":
        rc = cmd_prepare(fork_path, out_dir, define_unresolved=args.define_unresolved)
        if rc == 0:
            print(
                "\nWorktree staged. Run the build when authorised:\n"
                "  python scripts/assembly_smoke.py build"
            )
        return rc

    if args.cmd == "build":
        return cmd_build(out_dir)

    if args.cmd == "report":
        return cmd_report()

    if args.cmd == "teardown":
        return cmd_teardown(fork_path)

    # No subcommand given
    if args.prepare_only:
        rc = cmd_prepare(fork_path, out_dir, define_unresolved=args.define_unresolved)
        if rc == 0:
            print(
                "\nWorktree staged. Run the build when authorised:\n"
                "  python scripts/assembly_smoke.py build"
            )
        return rc

    # Default pipeline: prepare → build → report
    rc = cmd_prepare(fork_path, out_dir, define_unresolved=args.define_unresolved)
    if rc != 0:
        return rc
    rc_build = cmd_build(out_dir)
    rc_report = cmd_report()
    return 0 if (rc_build == 0 and rc_report == 0) else 1


if __name__ == "__main__":
    sys.exit(main())
