#!/usr/bin/env ruby
# Phase 0.4 — Dump Scripts.rxdata for custom mechanic survey
#
# Decompresses every script section from Scripts.rxdata and writes each to
# reference/scripts_dump/<NNN>_<Name>.rb for manual review.
# Also writes reference/scripts_index.md with a summary table flagging
# sections that appear non-standard (i.e., not vanilla Essentials).
#
# Usage:
#   RPG2GBA_URANIUM_SRC=/path/to/uranium ruby scripts/recon_scripts.rb

require 'zlib'
require 'fileutils'

uranium_src   = ENV['RPG2GBA_URANIUM_SRC'] or abort 'RPG2GBA_URANIUM_SRC not set'
scripts_path  = File.join(uranium_src, 'Data', 'Scripts.rxdata')
out_dir       = 'reference/scripts_dump'
index_path    = 'reference/scripts_index.md'

abort "Scripts.rxdata not found at #{scripts_path}" unless File.exist?(scripts_path)

FileUtils.mkdir_p(out_dir)

scripts = Marshal.load(File.binread(scripts_path))
puts "#{scripts.size} script sections found"

# Section names present in vanilla Pokémon Essentials (v15/v16 era).
# Anything not on this list is potentially Uranium-custom.
VANILLA = %w[
  Main PokemonMain PokemonUtilities PokemonMessages PokemonBitmapSprite
  PokemonText PokemonSystem PokemonSave PokemonLoad PokemonStartScreen
  PokemonPokeBattle PokemonBattle PokemonBattleCommon PokemonBattleAI
  PokemonMove PokemonMoveEffects PokemonItems PokemonItemEffects
  PokemonTrainers PokemonEncounters PokemonMap PokemonOverworldMoves
  PokemonField PokemonFieldMoves PokemonMenu PokemonPokedex PokemonSummary
  PokemonParty PokemonPC PokemonBag PokemonShop PokemonEvolution
  PokemonEgg PokemonForms PokemonMega PokemonHiddenMoves
  PokemonDebug PokemonTest PokemonVersion
  Interpreter Interpreter2 Interpreter3 Interpreter4 Interpreter5
  Interpreter6 Interpreter7
  Game_Temp Game_System Game_Switches Game_Variables Game_SelfSwitches
  Game_Screen Game_Troop Game_Map Game_CommonEvent Game_Character
  Game_Player Game_Event Game_Actor Game_Actors Game_Party
  Game_Battler Game_BattleAction Game_Enemy
  Scene_Map Scene_Battle Scene_Title Scene_Battle2 Scene_Battle3 Scene_Battle4
  Sprite_Character Sprite_Battler Spriteset_Map Spriteset_Battle
  Window_Base Window_Selectable Window_Command Window_Help
  Window_Gold Window_PlayTime Window_Steps Window_SaveFile
].map(&:downcase).to_set

index_lines = [
  '# Scripts.rxdata Index',
  '',
  'Auto-generated by `scripts/recon_scripts.rb`.',
  'Sections marked ⚠ are not in vanilla Essentials and likely contain Uranium-specific code.',
  '',
  '| # | Section | Lines | Notes |',
  '|---|---|---|---|',
]

scripts.each_with_index do |(_, name, compressed), i|
  begin
    source     = Zlib::Inflate.inflate(compressed)
    line_count = source.lines.size
    safe_name  = name.gsub(/[^\w\-]/, '_').gsub(/__+/, '_')
    out_file   = File.join(out_dir, format('%03d_%s.rb', i, safe_name))
    File.write(out_file, source, encoding: 'utf-8')

    flag = VANILLA.include?(name.downcase) ? '' : '⚠'
    index_lines << "| #{i} | `#{name}` | #{line_count} | #{flag} |"
  rescue => e
    index_lines << "| #{i} | `#{name}` | — | ERROR: #{e.message} |"
  end
end

File.write(index_path, index_lines.join("\n") + "\n")
puts "Scripts written to #{out_dir}/"
puts "Index written to #{index_path}"
