// DO NOT EDIT — generated by rpg2gba.pbs_converter.abilities
// source: dexdata.dat (ability refs) + Constants.rxdata
#ifndef GUARD_URANIUM_CONSTANTS_ABILITIES_H
#define GUARD_URANIUM_CONSTANTS_ABILITIES_H
// Uranium-original abilities only — these have no equivalent in the
// fork's ABILITY_* enum. Vanilla abilities are referenced directly by
// gSpeciesInfo[] and are NOT redefined here. NOTE: these are Uranium's
// own ability IDs and overlap vanilla numbering — V6 integration must
// reconcile them with the fork enum.
#define ABILITY_SHARP_CORAL 192
#define ABILITY_LAZY 193
#define ABILITY_REBUILD 194
#define ABILITY_PETRIFY 195
#define ABILITY_INFURIATE 196
#define ABILITY_ELEMENTALIST 197
#define ABILITY_ENERGIZATE 198
#define ABILITY_ACCELERATION 199
#define ABILITY_BLOOD_LUST 200
#define ABILITY_ATOMIZATE 201
#define ABILITY_LEAD_SKIN 202
#define ABILITY_DEEP_FREEZE 203
#define ABILITY_STORMBRINGER 204
#define ABILITY_QUICK_CHARGE 205
#define ABILITY_SOUND_BOOST 206
#define ABILITY_DISENCHANT 207
#define ABILITY_GEIGER_SENSE 208
#define ABILITY_CHERNOBYL 209
#define ABILITY_NIGHT_TERROR 210

#endif // GUARD_URANIUM_CONSTANTS_ABILITIES_H
