// DO NOT EDIT — generated by rpg2gba.pbs_converter.metadata
// source: metadata.dat (global Home record)
#ifndef GUARD_URANIUM_CONSTANTS_METADATA_H
#define GUARD_URANIUM_CONSTANTS_METADATA_H
// Player start position (Uranium map id + tile x/y + facing direction).
#define URANIUM_START_MAP 49
#define URANIUM_START_X 7
#define URANIUM_START_Y 7
#define URANIUM_START_DIR 2

#endif // GUARD_URANIUM_CONSTANTS_METADATA_H
