// === uranium_trainer_front_pic_ids.h ===
// DO NOT EDIT — generated by rpg2gba.trainer_converter.stage
// source: SLICE_TRAINER_PICS (common.py)
// #define chain, NOT enum members -- see module docstring / stage.py:
// tools/preproc's enum scanner can't follow an #include inside an enum
// body ("unterminated enum"). Do not move this into enum TrainerPicID.

#define TRAINER_PIC_FRONT_URANIUM_RIVAL   (TRAINER_PIC_COUNT + 0)
#define URANIUM_TRAINER_PIC_AFTER_FRONT   (TRAINER_PIC_COUNT + 1)

// === uranium_trainer_back_pic_ids.h ===
// DO NOT EDIT — generated by rpg2gba.trainer_converter.stage
// source: SLICE_TRAINER_PICS (common.py)
// #define chain, NOT enum members -- see module docstring / stage.py:
// tools/preproc's enum scanner can't follow an #include inside an enum
// body ("unterminated enum"). Do not move this into enum TrainerPicID.

#ifndef URANIUM_TRAINER_PIC_AFTER_FRONT
#define URANIUM_TRAINER_PIC_AFTER_FRONT   TRAINER_PIC_COUNT
#endif

#define TRAINER_PIC_BACK_URANIUM_PLAYER_MALE   (URANIUM_TRAINER_PIC_AFTER_FRONT + 0)
#define URANIUM_TRAINER_PIC_TOTAL              (URANIUM_TRAINER_PIC_AFTER_FRONT + 1)

#define URANIUM_HAVE_PLAYER_BACK_PIC

// === uranium_trainer_graphics.h ===
// DO NOT EDIT — generated by rpg2gba.trainer_converter.stage
// source: SLICE_TRAINER_PICS asset layout (common.py)

const u32 gTrainerFrontPic_Rival[] = INCGFX_U32("graphics/trainers/uranium/slice1/front.png", ".4bpp.smol");
const u16 gTrainerPalette_Rival[] = INCGFX_U16("graphics/trainers/uranium/slice1/front.pal", ".gbapal");

const u8 gTrainerBackPic_PlayerMale[] = INCGFX_U8("graphics/trainers/uranium/slice1/back.png", ".4bpp");
const u16 gTrainerBackPicPalette_PlayerMale[] = INCGFX_U16("graphics/trainers/uranium/slice1/back.pal", ".gbapal");

// Dedicated back-pic animation table for Uranium's back sheets -- do NOT
// reuse the stock sBackAnims_Hoenn here. sBackAnims_Hoenn[0] (the
// default/idle slot) is sAnim_GeneralFrame3 because vanilla's Hoenn back
// sheets put the idle pose at frame index 3. Our converted Uranium sheets
// are idle-FIRST (0 = idle, 1 = raise ball, 2 = windup, 3 = throw), so
// sBackAnims_Hoenn[0] would statically display our throw frame (index 3)
// instead of the idle pose -- the reported "static throw pose" bug.
// Self-contained: defines its own idle command rather than referencing
// sAnim_GeneralFrame0, since this header is #include'd before those stock
// tables are declared.
static const union AnimCmd sAnim_UraniumBackIdle[] =
{
    ANIMCMD_FRAME(0, 1),
    ANIMCMD_END,
};

static const union AnimCmd sAnimCmd_UraniumBackThrow[] =
{
    ANIMCMD_FRAME(0, 24),
    ANIMCMD_FRAME(1, 9),
    ANIMCMD_FRAME(2, 24),
    ANIMCMD_FRAME(3, 50),
    ANIMCMD_END,
};

static const union AnimCmd *const sBackAnims_Uranium[] =
{
    sAnim_UraniumBackIdle,
    sAnimCmd_UraniumBackThrow,
    sAnim_UraniumBackIdle,
};

// === uranium_trainer_sprites.h ===
// DO NOT EDIT — generated by rpg2gba.trainer_converter.stage
// source: SLICE_TRAINER_PICS (common.py)

    TRAINER_SPRITE(TRAINER_PIC_FRONT_URANIUM_RIVAL, gTrainerFrontPic_Rival, gTrainerPalette_Rival),

// === uranium_trainer_backsprites.h ===
// DO NOT EDIT — generated by rpg2gba.trainer_converter.stage
// source: SLICE_TRAINER_PICS (common.py)

    TRAINER_BACK_SPRITE(TRAINER_PIC_BACK_URANIUM_PLAYER_MALE, 4, gTrainerBackPic_PlayerMale, gTrainerBackPicPalette_PlayerMale, sBackAnims_Uranium),
